### ISSUE TITLE
WordPress plugin cannot connect to EA installation on other server

### ISSUE THREAD

**Issue by joho1968** [alextselegidis/easyappointments-wordpress#36]
Not sure if this has been covered before, but I'm somewhat confused as to how I'm supposed to integrate EA with the WordPress plugin.

I have EA on server1 and a WordPress site on server2.

In the WordPress plugin, I enter nothing in the path field (because it's installed on server1), and then the URL in the URL field. 

Then I click "CONNECT", and am given this in return:

"The AJAX request could not be completed due to an unexpected error: undefined"

In the PHP log, I see this:

`[16-Jan-2023 13:06:42 UTC] PHP Fatal error:  Uncaught Exception: Provided path does not point to an Easy!Appointments installation: "" in /var/www/server2.com/public_html/wp-content/plugins/easyappointments/admin/class-easyappointments-admin.php:185
Stack trace:
#0 /var/www/server2.com/public_html/wp-includes/class-wp-hook.php(308): Easyappointments_Admin->connect('')
#1 /var/www/server2.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /var/www/server2.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /var/www/server2.com/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_easyapp...')
#4 {main}
  thrown in /var/www/server2.com/public_html/wp-content/plugins/easyappointments/admin/class-easyappointments-admin.php on line 185`

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this. 

Could you please let me know which WP version are you using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Closing this due to inactivity. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by joho1968** [comment]
> Hello!
> Thanks for posting this.
> Could you please let me know which WP version are you using?

Sorry, I completely missed your initial response. This happens with WP 6.x.

**Comment by alextselegidis** [comment]
Thanks, I will check this and update accordingly.

**Comment by alextselegidis** [comment]
Hello! The plugin has ever since be updated so that the offending check does not take place and as such there is no issue. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
